# Generated by Django 5.2.6 on 2025-12-01 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_mentorbalance_mentorbalancehistory_withdrawrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformBalanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
