# Generated by Django 5.2.6 on 2025-12-03 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_platformbalance_platformbalancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawrequest',
            name='multicard_transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='multicard_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
