# Generated by Django 5.2.6 on 2025-12-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_withdrawrequest_multicard_transaction_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.IntegerField(editable=False),
        ),
    ]
