# Generated by Django 5.2.6 on 2025-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='valid_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
