# Generated by Django 5.2.6 on 2025-11-30 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='completion_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discount',
            name='max_usage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='discount',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
    ]
