# Generated by Django 5.2.6 on 2025-11-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_discount_completion_promo_discount_max_usage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='completion_promo',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='max_usage',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='usage_count',
        ),
        migrations.AddField(
            model_name='discount',
            name='usage_limit',
            field=models.PositiveIntegerField(default=1, help_text='Promo code usage limit'),
        ),
        migrations.AddField(
            model_name='discount',
            name='used_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times the code has been used'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='source',
            field=models.CharField(choices=[('PROMO', 'Promo Code'), ('HOLIDAY', 'Holiday Discount'), ('COMPLETION', 'Completion Promo')], max_length=20),
        ),
    ]
