# Generated by Django 5.2.6 on 2025-11-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_remove_discount_completion_promo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='usage_limit',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='used_count',
        ),
        migrations.AddField(
            model_name='discount',
            name='max_usage',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='discount',
            name='source',
            field=models.CharField(choices=[('PROMO', 'Promo Code'), ('HOLIDAY', 'Holiday Discount')], max_length=20),
        ),
    ]
