# Generated by Django 5.2.6 on 2025-11-30 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_remove_discount_usage_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='max_usage',
        ),
        migrations.AddField(
            model_name='discount',
            name='completion_promo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='max_discount',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='event',
            name='min_discount',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='discount',
            name='value',
            field=models.PositiveIntegerField(help_text='Chegirma foizi yoki flat miqdor', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
