# Generated by Django 5.2.6 on 2025-11-27 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio_uz', models.TextField(blank=True, max_length=500)),
                ('bio_ru', models.TextField(blank=True, max_length=500)),
                ('expertise', models.CharField(blank=True, max_length=200)),
                ('qualifications_uz', models.TextField(blank=True, max_length=1000)),
                ('qualifications_ru', models.TextField(blank=True, max_length=1000)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='instructors/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
