# Generated by Django 5.2.6 on 2025-11-30 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_instructorprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstructorProfile',
        ),
    ]
