# Generated by Django 5.2.6 on 2025-12-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_customuser_full_name_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Birth Date'),
        ),
        migrations.AddField(
            model_name='mentorprofile',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
