# Generated by Django 5.2.6 on 2025-12-04 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_mentorprofile_dob_mentorprofile_pinfl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorprofile',
            old_name='passport_issue_date',
            new_name='passport_expiration_date',
        ),
    ]
