# Generated by Django 5.2.6 on 2025-12-04 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_passport_issue_date_mentorprofile_passport_expiration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorprofile',
            name='passport_issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
