# Generated by Django 5.2.6 on 2025-12-04 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_mentorprofile_passport_issue_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentorprofile',
            old_name='passport_expiration_date',
            new_name='passport_expiry_date',
        ),
    ]
