# Generated by Django 5.2.6 on 2025-12-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_passport_expiration_date_mentorprofile_passport_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorcontract',
            name='is_signed',
            field=models.BooleanField(default=False),
        ),
    ]
