# Generated by Django 5.2.6 on 2025-12-06 06:41

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_mentorcontract_is_signed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorcontract',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/', location='/home/dilshod/projects/neosoft edu/edu-neosoft-api/private/contracts'), upload_to=''),
        ),
    ]
