# Generated by Django 5.2.6 on 2025-12-06 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_mentorcontract_pdf_file'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructorprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='instructorprofile',
            name='mentor',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_profile', to='authentication.mentorprofile'),
        ),
    ]
