# Generated by Django 5.2.6 on 2025-12-06 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_instructorprofile_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='title_uz',
        ),
    ]
